version: '3.7'

services:
  backend:
    build: .
    ports:
      - '3001:3001'
    env_file: [./.env]
    volumes:
      - ./backend/:/app
    working_dir: /app
    tty: true
  minio:
    image: minio/minio:latest
    ports:
      - 9000:9000
    volumes:
      - ./data/minio/data:/export
      - ./data/minio/config:/root/.minio
    environment:
      MINIO_ACCESS_KEY: MINIO_ACCESS_KEY
      MINIO_SECRET_KEY: minio_secret_key
    command: server /export 
  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc config host add myminio http://minio:9000 MINIO_ACCESS_KEY minio_secret_key) do echo '...waiting...' && sleep 1; done;
      /usr/bin/mc mb myminio/mybucket;
      /usr/bin/mc policy download myminio/mybucket;
      exit 0;
      "
  mysql:
    image: mysql:5.6
    container_name: some-mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=katayanagi-dojo
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --innodb_file_per_table
      --innodb_file_format=BARRACUDA
      --innodb_large_prefix=1

  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      ports:
        - 8000:80
      environment:
        - PMA_HOST=mysql
        - PMA_PASSWORD=root
        - PMA_USER=root
        - PMA_ARBITRARY=1
      links:
        - mysql
      depends_on:
        - mysql
