settings:
  legacy:
    force: true
    interval: 0s
schema:
- name: local
  path: .
  commands:
    install:
      status: true
      method: go build main.go
    run:
      status: true
      method: ./main
  watcher:
    extensions:
    - go
    paths:
    - .
    ignored_paths:
    - .git
    - .realize
    - vendor